### PR TITLE
Update cc-test-reporter setup

### PR DESCRIPTION
**Pull request by ale7714**
Follow up on https://github.com/codeclimate/test-reporter/pull/218, we
recently updated the test reporter to correctly parse source tags
when available.

### CODE REVIEW

**Comment by ale7714** [comment]
PS: now that file paths are parse and uploaded correctly to Code Climate, you can take advantage of the [browser extension](https://codeclimate.com/browser-extension/) to see the coverage overlay on the source code in GitHub.

**Comment by koraktor** [comment]
Thanks. Looks good to me despite the failed Travis build. This is only due to Travis’ new build images which no longer support Oracle JDK 7.

**Comment by koraktor** [comment]
@ale7714 But coverage data is still not showing up on Code Climate (https://codeclimate.com/github/koraktor/mavanagaiata/coverage).

**Comment by ale7714** [comment]
@koraktor i think this maybe not well explained, but currently the website is only showing coverage results for the default branch (master in your case). But you can use the extension to see your coverage. For example:

screen shot 2017-09-06 at 9 31 04 am

Having the coverage on GitHub is really useful specially when reviewing code in PRs 😅

**Pull request merged**
