### PR TITLE
Add support for skipping commits in changelog that contain a string

### PR DESCRIPTION
**Pull request by jeffkreska**

### CODE REVIEW

**Comment by koraktor** [comment]
Thanks.
I like the idea, but your commit introduces some unrelated changes.

Would you mind amending that commit with the following changes:

- Do not change the version
- Do not add IDE specific paths to `.gitignore`
- Do not reorganize imports unrelated to your change

**Comment by jeffkreska** [comment]
Sure. Sorry about imports my ide does it automatically.

Sent from my iPhone

On Mar 16, 2016, at 4:31 AM, Sebastian Staudt <notifications@github.com>
wrote:

Thanks.
I like the idea, but your commit introduces some unrelated changes.

Would you mind amending that commit with the following changes:

   - Do not change the version
   - Do not add IDE specific paths to .gitignore
   - Do not reorganize imports unrelated to your change

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/koraktor/mavanagaiata/pull/41#issuecomment-197226745>

**Comment by jeffkreska** [comment]
Incorporated your requests into my change.

**Comment by koraktor** [comment]
Thanks, I'll merge it soon.

**Pull request merged**
